name: sharing_cooks
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to 
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  async_redux: ^20.0.2
  build_runner: ^2.3.3
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  fl_country_code_picker: ^0.1.5
  flutter:
    sdk: flutter
  
  flutter_animation_progress_bar: ^2.3.1
  flutter_dotenv: ^5.0.2
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  flexible_carousel_slider: ^0.0.1
  flutter_graphql_client: ^0.2.2
  flutter_polyline_points: ^1.0.0
  flutter_svg: ^ 2.0.7
  # geolocator: ^9.0.2
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.2.3
  google_places_flutter: ^2.0.5
  http: ^0.13.6
  image_picker: ^1.0.2
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  pin_code_fields: ^7.4.0
  quiver: ^3.2.1
  sentry_flutter: ^6.18.2
  smooth_page_indicator: ^1.0.0+2
  sqflite: ^2.2.3
  supabase_flutter: ^1.3.1
  provider: ^6.0.3
  flutter_riverpod: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/images/

  uses-material-design: true

